Description: S3 bucket CSV storage

Parameters:
  BucketName:
    Description: Name of the s3 bucket
    Type: String

  AccountId:
    Description: AWS account ID
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  Bucket:
    Value: !Ref Bucket
